services:
  git:
    image: aliolozy/tinygit:latest
    container_name: git
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./git-repos:/git
    environment:
      - AUTH_ENABLE=false

  helm-repo:
    image: nginx:alpine
    container_name: helm-repo
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./helm-charts:/usr/share/nginx/html:ro